export const users = [
  {
    id: 1,
    name: "Malynda Roll",
    email: "mroll0@t.co",
    role: "user",
  },
  {
    id: 2,
    name: "Odella Atger",
    email: "oatger1@ucoz.com",
    role: "deliver",
  },
  {
    id: 3,
    name: "Lazaro Kernock",
    email: "lkernock2@theguardian.com",
    role: "admin",
  },
  {
    id: 4,
    name: "Rufe Cadle",
    email: "rcadle3@senate.gov",
    role: "deliver",
  },
  {
    id: 5,
    name: "Vincents Daft",
    email: "vdaft4@washingtonpost.com",
    role: "deliver",
  },
];

export const products = [
  {
    id: 3799150,
    product_name: "Tilapia - Fillets",
    category: "mujeres",
    size: "M",
    color: "Orange",
    price: 708904,
    quantity: 381,
  },
  {
    id: 28397733,
    product_name: "Pork - Smoked Back Bacon",
    category: "cosas",
    size: "L",
    color: "Orange",
    price: 862143,
    quantity: 420,
  },
  {
    id: 38621593,
    product_name: "Wine - Alicanca Vinho Verde",
    category: "hombres",
    size: "S",
    color: "Green",
    price: 33357,
    quantity: 817,
  },
  {
    id: 18538083,
    product_name: "Bread - Pita, Mini",
    category: "hombres",
    size: "XL",
    color: "Mauv",
    price: 293115,
    quantity: 863,
  },
  {
    id: 35451292,
    product_name: "Filter - Coffee",
    category: "mujeres",
    size: "L",
    color: "Purple",
    price: 520357,
    quantity: 824,
  },
  {
    id: 91088863,
    product_name: "Soda Water - Club Soda, 355 Ml",
    category: "cosas",
    size: "M",
    color: "Blue",
    price: 501203,
    quantity: 398,
  },
  {
    id: 8901059,
    product_name: "Amarula Cream",
    category: "mujeres",
    size: "Null",
    color: "Purple",
    price: 324180,
    quantity: 64,
  },
  {
    id: 14359808,
    product_name: "Grapefruit - White",
    category: "cosas",
    size: "XL",
    color: "Crimson",
    price: 98426,
    quantity: 958,
  },
  {
    id: 64229427,
    product_name: "Shrimp - 21/25, Peel And Deviened",
    category: "mujeres",
    size: "S",
    color: "Khaki",
    price: 617904,
    quantity: 498,
  },
  {
    id: 92179142,
    product_name: "Flower - Dish Garden",
    category: "cosas",
    size: "S",
    color: "Yellow",
    price: 867273,
    quantity: 108,
  },
  {
    id: 61986014,
    product_name: "Cheese - Goat",
    category: "cosas",
    size: "M",
    color: "Crimson",
    price: 665345,
    quantity: 724,
  },
  {
    id: 66174934,
    product_name: "Spring Roll Veg Mini",
    category: "cosas",
    size: "S",
    color: "Indigo",
    price: 349228,
    quantity: 959,
  },
  {
    id: 5348743,
    product_name: "Pork - Backfat",
    category: "cosas",
    size: "M",
    color: "Turquoise",
    price: 496524,
    quantity: 237,
  },
  {
    id: 94741455,
    product_name: "Potatoes - Idaho 80 Count",
    category: "mujeres",
    size: "Null",
    color: "Red",
    price: 567085,
    quantity: 312,
  },
  {
    id: 81491829,
    product_name: "Lotus Rootlets - Canned",
    category: "hombres",
    size: "M",
    color: "Green",
    price: 920839,
    quantity: 903,
  },
  {
    id: 55154027,
    product_name: "Ginsing - Fresh",
    category: "cosas",
    size: "L",
    color: "Goldenrod",
    price: 441310,
    quantity: 49,
  },
  {
    id: 93855696,
    product_name: "Table Cloth 72x144 White",
    category: "hombres",
    size: "Null",
    color: "Puce",
    price: 54716,
    quantity: 718,
  },
  {
    id: 37899587,
    product_name: "Orange - Canned, Mandarin",
    category: "cosas",
    size: "L",
    color: "Mauv",
    price: 640647,
    quantity: 266,
  },
  {
    id: 88135815,
    product_name: "Buttons",
    category: "hombres",
    size: "L",
    color: "Goldenrod",
    price: 75718,
    quantity: 55,
  },
  {
    id: 45191941,
    product_name: "Truffle Cups - Red",
    category: "cosas",
    size: "L",
    color: "Mauv",
    price: 432142,
    quantity: 991,
  },
];
